/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BttnRecruit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttnlogin = new javax.swing.JButton();
        showpass = new javax.swing.JCheckBox();
        jpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        Lusername2 = new javax.swing.JLabel();
        Lpassword = new javax.swing.JLabel();
        mainbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText("Ninja Student Record");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        BttnRecruit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BttnRecruit.setForeground(new java.awt.Color(255, 255, 255));
        BttnRecruit.setText("Register Now!");
        BttnRecruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnRecruitMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't have an Account?");

        bttnlogin.setBackground(new java.awt.Color(230, 74, 25));
        bttnlogin.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 21)); // NOI18N
        bttnlogin.setForeground(new java.awt.Color(255, 255, 255));
        bttnlogin.setText("Login");
        bttnlogin.setMaximumSize(new java.awt.Dimension(110, 40));
        bttnlogin.setMinimumSize(new java.awt.Dimension(110, 40));
        bttnlogin.setPreferredSize(new java.awt.Dimension(110, 40));
        bttnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnloginActionPerformed(evt);
            }
        });

        showpass.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });

        jpassword.setBackground(new java.awt.Color(51, 51, 51));
        jpassword.setForeground(new java.awt.Color(255, 255, 255));
        jpassword.setToolTipText("");
        jpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        txtusername.setBackground(new java.awt.Color(51, 51, 51));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        Lusername2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Lusername2.setForeground(new java.awt.Color(255, 255, 255));
        Lusername2.setText("Username");

        Lpassword.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Lpassword.setForeground(new java.awt.Color(255, 255, 255));
        Lpassword.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lpassword)
                            .addComponent(Lusername2)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showpass, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BttnRecruit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Lusername2)
                .addGap(12, 12, 12)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(showpass)
                .addGap(31, 31, 31)
                .addComponent(bttnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BttnRecruit))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 390, 370));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Naruto-Signup-background.jpg"))); // NOI18N
        getContentPane().add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            jpassword.setEchoChar((char)0); //I reveal ang password
        }else {
            jpassword.setEchoChar('*');//Taguan ang password
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void bttnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnloginActionPerformed
//        String user = txtusername.getText().trim();
//        String pass = new String(jpassword.getPassword()).trim();
//
//        if (user.isEmpty() || pass.isEmpty()) {
//            JOptionPane.showMessageDialog(this,
//                "Please enter your username and password!.",
//                "Login Failed", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        try{
//            String url = "jdbc:mysql://localhost/demon_slayer_db";
//            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");
//
//            String sql = "SELECT * FROM users Where username=? AND password=?";
//            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//            pst.setString(1, user);
//            pst.setString(2, pass);
//
//            java.sql.ResultSet rs = pst.executeQuery();
//
//            if(rs.next()) {
//                //kung makita ang account
//                JOptionPane.showMessageDialog(this , "Access Granted. Welcome, " + user);
//
//                Dashboard dash = new Dashboard();
//                dash.setVisible(true);
//                this.dispose();
//            }else {
//                //kung wala nakita ang account
//                JOptionPane.showMessageDialog(this, "Incorrect password", "Login Failed", JOptionPane.ERROR_MESSAGE);
//            }
//            conn.close();
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Error reading users file", "Error", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_bttnloginActionPerformed

    private void BttnRecruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnRecruitMouseClicked
        Register reg = new Register();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BttnRecruitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BttnRecruit;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lusername2;
    private javax.swing.JButton bttnlogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel mainbg;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
